### ISSUE TITLE
Cannot import name spawn

### ISSUE THREAD

**Issue by jaimelaborda** [geertj/winpexpect#2]
> from winpexpect import winspawn, TIMEOUT, ExceptionPexpect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\es04080213\AppData\Local\Continuum\Anaconda2\lib\site-packages\winpexpect.py", line 18, in <module>
    from pexpect import spawn, ExceptionPexpect, EOF, TIMEOUT
ImportError: cannot import name spawn

**Comment by newlog** [comment]
Make sure you don't have the original pexpect installed.
