### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbb in position 19: ordinal not in range(128)

### ISSUE THREAD

**Issue by dewey2** [geertj/winpexpect#4]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "E:\python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\site-packages\winpexpect.py", line 511, in _child_reader
    err, data = ReadFile(handle, self.maxread)
  File "E:\python\lib\site-packages\winpexpect.py", line 64, in ReadFile
    return err, data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbb in position 19: ordinal not in range(128)

**Comment by dewey2** [comment]
```
python
# Compatbility wiht Python 3
if sys.version_info[0] == 3:

    _WriteFile = WriteFile
    def WriteFile(handle, s):
        return _WriteFile(handle, s.encode('ascii'))

    _ReadFile = ReadFile
    def ReadFile(handle, size):
        err, data = _ReadFile(handle, size)
        return err, data.decode('ascii', errors='ignore')```
